import js from '@eslint/js'
import globals from 'globals'
import reactHooks from 'eslint-plugin-react-hooks'
import reactRefresh from 'eslint-plugin-react-refresh'
import { defineConfig, globalIgnores } from 'eslint/config'

export default defineConfig([
  // `.ai` is the ogen-ai submodule; the rest are the per-tool skill trees
  // ai-sync copies out of it. Vendored config, regenerated by
  // `python .ai/bin/ai-sync` — not this repo's code to lint.
  globalIgnores(['dist', '.ai', '.agents', '.claude', '.cursor', '.github/skills']),
  {
    files: ['**/*.{js,jsx}'],
    extends: [
      js.configs.recommended,
      reactHooks.configs.flat.recommended,
      reactRefresh.configs.vite,
    ],
    languageOptions: {
      globals: globals.browser,
      parserOptions: { ecmaFeatures: { jsx: true } },
    },
    rules: {
      // Pre-existing patterns (localStorage sync effects, drag handlers that close
      // over refs). Tracked for a later cleanup — warn so `npm run lint` can gate
      // CI without failing on these React Compiler–style rules today.
      'react-hooks/set-state-in-effect': 'warn',
      'react-hooks/refs': 'warn',
    },
  },
  {
    files: [
      'playwright.config.js',
      'vite.config.js',
      'eslint.config.js',
      'src/__tests__/**/*.{js,jsx}',
      'src/services/aiAssistant.js',
      'e2e/screenshots.spec.js',
    ],
    languageOptions: {
      globals: { ...globals.browser, ...globals.node },
    },
  },
])
